"""
coder_agent.py
==============
Role: Coder Agent
Responsibility:
    Consumes a ``HardwareSpec`` produced by the Planner Agent and generates
    production-quality C/C++ source code that follows either the ESP-IDF or
    STM32 HAL library conventions, wrapped with FreeRTOS task primitives.

LLM backend
-----------
Real deployments should replace ``mock_doubao_call`` with an authenticated
call to the ByteDance Doubao (or equivalent) API.  The mock returns
syntactically complete C code that the Reviewer Agent can analyse.

Output contract
---------------
A single string containing the complete C/C++ source file, ready to be
written to disk as ``<task_name>.c``.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Optional

HardwareSpec = Dict[str, Any]


# ---------------------------------------------------------------------------
# Mock LLM back-end
# ---------------------------------------------------------------------------

def mock_doubao_call(system_prompt: str, user_message: str) -> str:
    """
    Simulate a ByteDance Doubao API call.

    In production replace the body of this function with:

        import openai  # Doubao is OpenAI-API-compatible
        client = openai.OpenAI(
            api_key=os.environ["DOUBAO_API_KEY"],
            base_url="https://ark.cn-beijing.volces.com/api/v3",
        )
        response = client.chat.completions.create(
            model="doubao-pro-128k",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_message},
            ],
        )
        return response.choices[0].message.content

    The mock inspects the spec JSON embedded in ``user_message`` and returns
    realistic C code that covers all common peripheral templates.
    """
    # Extract the JSON spec from the user message.
    # Use a JSONDecoder that stops at the end of the first complete object,
    # ignoring any trailing prose that follows the spec in the prompt.
    spec: HardwareSpec = {}
    try:
        json_start = user_message.index("{")
        decoder = json.JSONDecoder()
        spec, _ = decoder.raw_decode(user_message, json_start)
    except (ValueError, json.JSONDecodeError):
        spec = {}

    mcu: str = spec.get("mcu", "ESP32")
    rtos: str = spec.get("rtos", "FreeRTOS")
    peripherals: list = spec.get("peripherals", [])
    tasks: list = spec.get("tasks", [])
    memory: dict = spec.get("memory", {})

    interface = (peripherals[0].get("interface", "GPIO") if peripherals else "GPIO").upper()
    task_name = tasks[0].get("name", "main_task") if tasks else "main_task"
    stack_size = tasks[0].get("stack_size", 4096) if tasks else 4096
    priority = tasks[0].get("priority", 5) if tasks else 5
    period_ms = tasks[0].get("period_ms", 1000) if tasks else 1000
    heap_kb = memory.get("heap_kb", 16)

    # ------------------------------------------------------------------ I2C / OLED
    if interface == "I2C":
        pins = peripherals[0].get("pins", {}) if peripherals else {}
        sda = pins.get("SDA", "GPIO_NUM_21")
        scl = pins.get("SCL", "GPIO_NUM_22")
        i2c_addr = peripherals[0].get("address", "0x3C") if peripherals else "0x3C"

        code = f"""\
/**
 * @file    {task_name}.c
 * @brief   Auto-generated I2C / OLED display task for {mcu} ({rtos})
 *
 * Generated by CoderAgent — Multi-Agent Autonomous Coding & Verification Framework
 * Target MCU : {mcu}
 * RTOS       : {rtos}
 * Interface  : I2C (SDA={sda}, SCL={scl})
 * I2C Addr   : {i2c_addr}
 *
 * @warning  Review with ReviewerAgent before flashing to hardware.
 */

#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "driver/i2c.h"
#include "esp_log.h"

/* ── Configuration ─────────────────────────────────────────────────────── */
#define TAG                 "{task_name.upper()}"
#define I2C_MASTER_NUM      I2C_NUM_0
#define I2C_MASTER_SDA_IO   {sda}
#define I2C_MASTER_SCL_IO   {scl}
#define I2C_MASTER_FREQ_HZ  400000          /* 400 kHz Fast Mode              */
#define OLED_I2C_ADDR       {i2c_addr}
#define OLED_SCREEN_WIDTH   128
#define OLED_SCREEN_HEIGHT  64
#define FRAME_BUFFER_SIZE   (OLED_SCREEN_WIDTH * OLED_SCREEN_HEIGHT / 8U)
#define DISPLAY_PERIOD_MS   {period_ms}
#define TASK_STACK_SIZE     {stack_size}
#define TASK_PRIORITY       {priority}
#define HEAP_GUARD_SIZE     ({heap_kb} * 1024)

/* ── Globals ────────────────────────────────────────────────────────────── */
static SemaphoreHandle_t s_i2c_mutex = NULL;
static uint8_t          *s_frame_buffer = NULL;

/* ── I2C master initialisation ─────────────────────────────────────────── */
static esp_err_t i2c_master_init(void)
{{
    i2c_config_t conf = {{
        .mode             = I2C_MODE_MASTER,
        .sda_io_num       = I2C_MASTER_SDA_IO,
        .scl_io_num       = I2C_MASTER_SCL_IO,
        .sda_pullup_en    = GPIO_PULLUP_ENABLE,
        .scl_pullup_en    = GPIO_PULLUP_ENABLE,
        .master.clk_speed = I2C_MASTER_FREQ_HZ,
    }};

    esp_err_t err = i2c_param_config(I2C_MASTER_NUM, &conf);
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "i2c_param_config failed: %s", esp_err_to_name(err));
        return err;
    }}

    err = i2c_driver_install(I2C_MASTER_NUM, conf.mode,
                             0,   /* rx_buf_len — master mode: 0 */
                             0,   /* tx_buf_len — master mode: 0 */
                             0);  /* intr_alloc_flags              */
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "i2c_driver_install failed: %s", esp_err_to_name(err));
    }}
    return err;
}}

/* ── SSD1306 helpers ────────────────────────────────────────────────────── */
static esp_err_t oled_send_command(uint8_t cmd)
{{
    i2c_cmd_handle_t handle = i2c_cmd_link_create();
    if (handle == NULL) {{
        ESP_LOGE(TAG, "i2c_cmd_link_create returned NULL");
        return ESP_ERR_NO_MEM;
    }}

    esp_err_t err = ESP_OK;
    err |= i2c_master_start(handle);
    err |= i2c_master_write_byte(handle, (OLED_I2C_ADDR << 1) | I2C_MASTER_WRITE, true);
    err |= i2c_master_write_byte(handle, 0x00, true);  /* Co=0, D/C#=0 (command) */
    err |= i2c_master_write_byte(handle, cmd,  true);
    err |= i2c_master_stop(handle);

    if (err == ESP_OK) {{
        err = i2c_master_cmd_begin(I2C_MASTER_NUM, handle,
                                   pdMS_TO_TICKS(10));
    }}

    i2c_cmd_link_delete(handle);
    return err;
}}

static esp_err_t oled_init(void)
{{
    const uint8_t init_seq[] = {{
        0xAE,       /* Display OFF                    */
        0xD5, 0x80, /* Set display clock divide ratio */
        0xA8, 0x3F, /* Set multiplex ratio (1/64)     */
        0xD3, 0x00, /* Set display offset             */
        0x40,       /* Set display start line         */
        0x8D, 0x14, /* Charge pump ON                 */
        0x20, 0x00, /* Memory addressing mode: horizontal */
        0xA1,       /* Segment re-map                 */
        0xC8,       /* COM output scan direction      */
        0xDA, 0x12, /* Set COM pins                   */
        0x81, 0xCF, /* Set contrast                   */
        0xD9, 0xF1, /* Set pre-charge period          */
        0xDB, 0x40, /* Set VCOMH deselect level       */
        0xA4,       /* Resume RAM content             */
        0xA6,       /* Normal display                 */
        0xAF,       /* Display ON                     */
    }};

    for (size_t i = 0; i < sizeof(init_seq); i++) {{
        esp_err_t err = oled_send_command(init_seq[i]);
        if (err != ESP_OK) {{
            ESP_LOGE(TAG, "oled_init: command 0x%02X failed", init_seq[i]);
            return err;
        }}
    }}
    return ESP_OK;
}}

static esp_err_t oled_flush_buffer(const uint8_t *buf, size_t len)
{{
    if (buf == NULL) {{
        return ESP_ERR_INVALID_ARG;
    }}

    /* Set page/column addresses to cover entire display */
    oled_send_command(0x21);  /* Set column address */
    oled_send_command(0x00);
    oled_send_command(0x7F);
    oled_send_command(0x22);  /* Set page address   */
    oled_send_command(0x00);
    oled_send_command(0x07);

    i2c_cmd_handle_t handle = i2c_cmd_link_create();
    if (handle == NULL) {{
        return ESP_ERR_NO_MEM;
    }}

    esp_err_t err = ESP_OK;
    err |= i2c_master_start(handle);
    err |= i2c_master_write_byte(handle, (OLED_I2C_ADDR << 1) | I2C_MASTER_WRITE, true);
    err |= i2c_master_write_byte(handle, 0x40, true);  /* Co=0, D/C#=1 (data) */
    err |= i2c_master_write(handle, buf, len, true);
    err |= i2c_master_stop(handle);

    if (err == ESP_OK) {{
        err = i2c_master_cmd_begin(I2C_MASTER_NUM, handle,
                                   pdMS_TO_TICKS(50));
    }}

    i2c_cmd_link_delete(handle);
    return err;
}}

/* ── FreeRTOS Task ──────────────────────────────────────────────────────── */
static void {task_name}(void *pvParameters)
{{
    /* Acquire I2C bus mutex */
    if (xSemaphoreTake(s_i2c_mutex, pdMS_TO_TICKS(1000)) != pdTRUE) {{
        ESP_LOGE(TAG, "Failed to acquire I2C mutex during init");
        vTaskDelete(NULL);
        return;
    }}

    esp_err_t err = oled_init();
    xSemaphoreGive(s_i2c_mutex);

    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "OLED init failed — task exiting");
        vTaskDelete(NULL);
        return;
    }}

    ESP_LOGI(TAG, "OLED initialised — entering display loop");

    uint32_t frame = 0;

    for (;;) {{
        /* --- Update frame buffer --- */
        memset(s_frame_buffer, 0, FRAME_BUFFER_SIZE);

        /* Simple animated pattern: invert alternating rows per frame */
        for (int page = 0; page < 8; page++) {{
            uint8_t fill = ((page + frame) % 2 == 0) ? 0xFF : 0x00;
            memset(&s_frame_buffer[page * OLED_SCREEN_WIDTH], fill, OLED_SCREEN_WIDTH);
        }}

        /* --- Flush to display under mutex --- */
        if (xSemaphoreTake(s_i2c_mutex, pdMS_TO_TICKS(100)) == pdTRUE) {{
            err = oled_flush_buffer(s_frame_buffer,
                                    FRAME_BUFFER_SIZE);
            xSemaphoreGive(s_i2c_mutex);

            if (err != ESP_OK) {{
                ESP_LOGW(TAG, "Display flush error: %s", esp_err_to_name(err));
            }}
        }} else {{
            ESP_LOGW(TAG, "Could not acquire I2C mutex for flush");
        }}

        frame++;
        vTaskDelay(pdMS_TO_TICKS(DISPLAY_PERIOD_MS));
    }}
    /* Tasks must not return; vTaskDelete called if loop exits */
    vTaskDelete(NULL);
}}

/* ── Application entry point ────────────────────────────────────────────── */
void app_main(void)
{{
    ESP_LOGI(TAG, "Initialising I2C master bus");

    esp_err_t err = i2c_master_init();
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "I2C master init failed — halting");
        return;
    }}

    /* Create shared I2C mutex */
    s_i2c_mutex = xSemaphoreCreateMutex();
    if (s_i2c_mutex == NULL) {{
        ESP_LOGE(TAG, "Failed to create I2C mutex — halting");
        return;
    }}

    /* Allocate display frame buffer — guarded heap allocation */
    s_frame_buffer = (uint8_t *)pvPortMalloc(
        FRAME_BUFFER_SIZE);
    if (s_frame_buffer == NULL) {{
        ESP_LOGE(TAG, "Frame buffer allocation failed — halting");
        vSemaphoreDelete(s_i2c_mutex);
        return;
    }}
    memset(s_frame_buffer, 0, FRAME_BUFFER_SIZE);

    xTaskCreate({task_name},
                "{task_name}",
                TASK_STACK_SIZE,
                NULL,
                TASK_PRIORITY,
                NULL);

    ESP_LOGI(TAG, "{task_name} created (stack={stack_size}, priority={priority})");
}}
"""

    # ------------------------------------------------------------------ SPI
    elif interface == "SPI":
        pins = peripherals[0].get("pins", {}) if peripherals else {}
        mosi = pins.get("MOSI", "GPIO_NUM_23")
        miso = pins.get("MISO", "GPIO_NUM_19")
        sclk = pins.get("SCLK", "GPIO_NUM_18")
        cs   = pins.get("CS",   "GPIO_NUM_5")

        code = f"""\
/**
 * @file    {task_name}.c
 * @brief   Auto-generated SPI transfer task for {mcu} ({rtos})
 *
 * Generated by CoderAgent — Multi-Agent Autonomous Coding & Verification Framework
 * Target MCU : {mcu}
 * RTOS       : {rtos}
 * Interface  : SPI (MOSI={mosi}, MISO={miso}, SCLK={sclk}, CS={cs})
 */

#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "driver/spi_master.h"
#include "driver/gpio.h"
#include "esp_log.h"

#define TAG              "{task_name.upper()}"
#define SPI_HOST         SPI2_HOST
#define SPI_MOSI_PIN     {mosi}
#define SPI_MISO_PIN     {miso}
#define SPI_SCLK_PIN     {sclk}
#define SPI_CS_PIN       {cs}
#define SPI_CLOCK_HZ     10000000          /* 10 MHz                         */
#define TRANSFER_SIZE_B  64
#define TRANSFER_PERIOD  {period_ms}
#define TASK_STACK_SIZE  {stack_size}
#define TASK_PRIORITY    {priority}

static spi_device_handle_t s_spi_handle = NULL;
static SemaphoreHandle_t   s_spi_sem    = NULL;

static esp_err_t spi_master_init(void)
{{
    spi_bus_config_t bus_cfg = {{
        .mosi_io_num   = SPI_MOSI_PIN,
        .miso_io_num   = SPI_MISO_PIN,
        .sclk_io_num   = SPI_SCLK_PIN,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = TRANSFER_SIZE_B,
    }};

    esp_err_t err = spi_bus_initialize(SPI_HOST, &bus_cfg, SPI_DMA_CH_AUTO);
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "spi_bus_initialize failed: %s", esp_err_to_name(err));
        return err;
    }}

    spi_device_interface_config_t dev_cfg = {{
        .clock_speed_hz = SPI_CLOCK_HZ,
        .mode           = 0,
        .spics_io_num   = SPI_CS_PIN,
        .queue_size     = 8,
    }};

    err = spi_bus_add_device(SPI_HOST, &dev_cfg, &s_spi_handle);
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "spi_bus_add_device failed: %s", esp_err_to_name(err));
    }}
    return err;
}}

static void {task_name}(void *pvParameters)
{{
    uint8_t tx_buf[TRANSFER_SIZE_B];
    uint8_t rx_buf[TRANSFER_SIZE_B];

    ESP_LOGI(TAG, "SPI transfer task started");

    for (;;) {{
        /* Populate TX buffer */
        for (int i = 0; i < TRANSFER_SIZE_B; i++) {{
            tx_buf[i] = (uint8_t)i;
        }}

        spi_transaction_t txn = {{
            .length    = TRANSFER_SIZE_B * 8,   /* bits */
            .tx_buffer = tx_buf,
            .rx_buffer = rx_buf,
        }};

        if (xSemaphoreTake(s_spi_sem, pdMS_TO_TICKS(100)) == pdTRUE) {{
            esp_err_t err = spi_device_polling_transmit(s_spi_handle, &txn);
            xSemaphoreGive(s_spi_sem);
            if (err != ESP_OK) {{
                ESP_LOGW(TAG, "SPI transmit error: %s", esp_err_to_name(err));
            }} else {{
                ESP_LOGD(TAG, "SPI transfer OK — first byte RX: 0x%02X", rx_buf[0]);
            }}
        }}

        vTaskDelay(pdMS_TO_TICKS(TRANSFER_PERIOD));
    }}
    vTaskDelete(NULL);
}}

void app_main(void)
{{
    esp_err_t err = spi_master_init();
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "SPI init failed");
        return;
    }}

    s_spi_sem = xSemaphoreCreateMutex();
    if (s_spi_sem == NULL) {{
        ESP_LOGE(TAG, "SPI semaphore creation failed");
        return;
    }}

    xTaskCreate({task_name}, "{task_name}", TASK_STACK_SIZE, NULL, TASK_PRIORITY, NULL);
}}
"""

    # ------------------------------------------------------------------ UART
    elif interface == "UART":
        code = f"""\
/**
 * @file    {task_name}.c
 * @brief   Auto-generated UART RX/TX tasks for {mcu} ({rtos})
 *
 * Generated by CoderAgent — Multi-Agent Autonomous Coding & Verification Framework
 * Target MCU : {mcu}
 * RTOS       : {rtos}
 * Interface  : UART2
 */

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/stream_buffer.h"
#include "driver/uart.h"
#include "esp_log.h"

#define TAG             "{task_name.upper()}"
#define UART_PORT       UART_NUM_2
#define UART_TX_PIN     GPIO_NUM_17
#define UART_RX_PIN     GPIO_NUM_16
#define UART_BAUD       115200
#define BUF_SIZE        256
#define TASK_STACK      {stack_size}
#define TASK_PRIO       {priority}

static StreamBufferHandle_t s_rx_stream = NULL;

static void uart_rx_task(void *pvParameters)
{{
    uint8_t data[BUF_SIZE];

    for (;;) {{
        int len = uart_read_bytes(UART_PORT, data, sizeof(data) - 1,
                                  pdMS_TO_TICKS(20));
        if (len > 0) {{
            data[len] = '\\0';
            xStreamBufferSend(s_rx_stream, data, (size_t)len,
                              pdMS_TO_TICKS(10));
            ESP_LOGI(TAG, "RX %d bytes", len);
        }}
    }}
    vTaskDelete(NULL);
}}

static void uart_tx_task(void *pvParameters)
{{
    uint8_t rx_data[BUF_SIZE];

    for (;;) {{
        size_t received = xStreamBufferReceive(s_rx_stream, rx_data,
                                               sizeof(rx_data) - 1,
                                               pdMS_TO_TICKS({period_ms}));
        if (received > 0) {{
            /* Echo back */
            uart_write_bytes(UART_PORT, (const char *)rx_data,
                             received);
        }}
    }}
    vTaskDelete(NULL);
}}

void app_main(void)
{{
    uart_config_t uart_cfg = {{
        .baud_rate  = UART_BAUD,
        .data_bits  = UART_DATA_8_BITS,
        .parity     = UART_PARITY_DISABLE,
        .stop_bits  = UART_STOP_BITS_1,
        .flow_ctrl  = UART_HW_FLOWCTRL_DISABLE,
    }};

    uart_driver_install(UART_PORT, BUF_SIZE * 2, 0, 0, NULL, 0);
    uart_param_config(UART_PORT, &uart_cfg);
    uart_set_pin(UART_PORT, UART_TX_PIN, UART_RX_PIN,
                 UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE);

    s_rx_stream = xStreamBufferCreate(BUF_SIZE * 4, 1);
    if (s_rx_stream == NULL) {{
        ESP_LOGE(TAG, "Stream buffer creation failed");
        return;
    }}

    xTaskCreate(uart_rx_task, "uart_rx", TASK_STACK, NULL, TASK_PRIO + 1, NULL);
    xTaskCreate(uart_tx_task, "uart_tx", TASK_STACK, NULL, TASK_PRIO,     NULL);
}}
"""

    # ------------------------------------------------------------------ GPIO / LED
    elif interface == "GPIO":
        code = f"""\
/**
 * @file    {task_name}.c
 * @brief   Auto-generated GPIO blink / button task for {mcu} ({rtos})
 *
 * Generated by CoderAgent — Multi-Agent Autonomous Coding & Verification Framework
 * Target MCU : {mcu}
 * RTOS       : {rtos}
 * Interface  : GPIO
 */

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/gpio.h"
#include "esp_log.h"

#define TAG          "{task_name.upper()}"
#define LED_GPIO     GPIO_NUM_2
#define BUTTON_GPIO  GPIO_NUM_0
#define BLINK_MS     {period_ms}
#define DEBOUNCE_MS  20
#define TASK_STACK   {stack_size}
#define TASK_PRIO    {priority}

static QueueHandle_t s_button_evt_queue = NULL;

static void IRAM_ATTR gpio_isr_handler(void *arg)
{{
    uint32_t gpio_num = (uint32_t)(uintptr_t)arg;
    xQueueSendFromISR(s_button_evt_queue, &gpio_num, NULL);
}}

static void blink_task(void *pvParameters)
{{
    gpio_set_direction(LED_GPIO, GPIO_MODE_OUTPUT);

    for (;;) {{
        gpio_set_level(LED_GPIO, 1);
        vTaskDelay(pdMS_TO_TICKS(BLINK_MS));
        gpio_set_level(LED_GPIO, 0);
        vTaskDelay(pdMS_TO_TICKS(BLINK_MS));
    }}
    vTaskDelete(NULL);
}}

static void button_task(void *pvParameters)
{{
    uint32_t io_num;
    TickType_t last_press = 0;

    for (;;) {{
        if (xQueueReceive(s_button_evt_queue, &io_num,
                          portMAX_DELAY) == pdTRUE) {{
            TickType_t now = xTaskGetTickCount();
            if ((now - last_press) > pdMS_TO_TICKS(DEBOUNCE_MS)) {{
                last_press = now;
                ESP_LOGI(TAG, "Button press detected on GPIO %lu",
                         (unsigned long)io_num);
            }}
        }}
    }}
    vTaskDelete(NULL);
}}

void app_main(void)
{{
    s_button_evt_queue = xQueueCreate(10, sizeof(uint32_t));
    if (s_button_evt_queue == NULL) {{
        ESP_LOGE(TAG, "Button queue creation failed");
        return;
    }}

    gpio_config_t io_conf = {{
        .pin_bit_mask = (1ULL << BUTTON_GPIO),
        .mode         = GPIO_MODE_INPUT,
        .pull_up_en   = GPIO_PULLUP_ENABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_NEGEDGE,
    }};
    gpio_config(&io_conf);

    gpio_install_isr_service(0);
    gpio_isr_handler_add(BUTTON_GPIO, gpio_isr_handler,
                         (void *)(uintptr_t)BUTTON_GPIO);

    xTaskCreate(blink_task,  "blink",  TASK_STACK, NULL, TASK_PRIO,     NULL);
    xTaskCreate(button_task, "button", TASK_STACK, NULL, TASK_PRIO + 1, NULL);
}}
"""

    # ------------------------------------------------------------------ ADC
    elif interface == "ADC":
        code = f"""\
/**
 * @file    {task_name}.c
 * @brief   Auto-generated ADC sampling task for {mcu} ({rtos})
 *
 * Generated by CoderAgent — Multi-Agent Autonomous Coding & Verification Framework
 * Target MCU : {mcu}
 * RTOS       : {rtos}
 * Interface  : ADC (12-bit)
 */

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "esp_adc/adc_oneshot.h"
#include "esp_log.h"

#define TAG              "{task_name.upper()}"
#define ADC_UNIT         ADC_UNIT_1
#define ADC_CHANNEL      ADC_CHANNEL_0
#define ADC_ATTEN        ADC_ATTEN_DB_11
#define MA_WINDOW        16
#define SAMPLE_PERIOD_MS {period_ms}
#define TASK_STACK       {stack_size}
#define TASK_PRIO        {priority}
#define VREF_MV          3300

static QueueHandle_t    s_result_queue = NULL;
static adc_oneshot_unit_handle_t s_adc_handle = NULL;

static int moving_average(int new_sample, int *window, int *idx, int *sum)
{{
    *sum -= window[*idx];
    window[*idx] = new_sample;
    *sum += new_sample;
    *idx = (*idx + 1) % MA_WINDOW;
    return *sum / MA_WINDOW;
}}

static void {task_name}(void *pvParameters)
{{
    int ma_window[MA_WINDOW];
    int ma_idx = 0, ma_sum = 0;
    memset(ma_window, 0, sizeof(ma_window));

    for (;;) {{
        int raw = 0;
        esp_err_t err = adc_oneshot_read(s_adc_handle, ADC_CHANNEL, &raw);
        if (err == ESP_OK) {{
            int filtered = moving_average(raw, ma_window, &ma_idx, &ma_sum);
            int voltage_mv = (filtered * VREF_MV) / 4095;
            xQueueSend(s_result_queue, &voltage_mv, 0);
            ESP_LOGD(TAG, "raw=%d filtered=%d voltage=%dmV",
                     raw, filtered, voltage_mv);
        }} else {{
            ESP_LOGW(TAG, "ADC read error: %s", esp_err_to_name(err));
        }}

        vTaskDelay(pdMS_TO_TICKS(SAMPLE_PERIOD_MS));
    }}
    vTaskDelete(NULL);
}}

void app_main(void)
{{
    adc_oneshot_unit_init_cfg_t init_cfg = {{
        .unit_id = ADC_UNIT,
    }};
    adc_oneshot_new_unit(&init_cfg, &s_adc_handle);

    adc_oneshot_chan_cfg_t chan_cfg = {{
        .atten      = ADC_ATTEN,
        .bitwidth   = ADC_BITWIDTH_12,
    }};
    adc_oneshot_config_channel(s_adc_handle, ADC_CHANNEL, &chan_cfg);

    s_result_queue = xQueueCreate(32, sizeof(int));
    if (s_result_queue == NULL) {{
        ESP_LOGE(TAG, "Result queue creation failed");
        return;
    }}

    xTaskCreate({task_name}, "{task_name}", TASK_STACK, NULL, TASK_PRIO, NULL);
}}
"""

    # ------------------------------------------------------------------ Generic
    else:
        code = f"""\
/**
 * @file    {task_name}.c
 * @brief   Auto-generated generic task template for {mcu} ({rtos})
 *
 * Generated by CoderAgent — Multi-Agent Autonomous Coding & Verification Framework
 * Target MCU : {mcu}
 * RTOS       : {rtos}
 */

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"

#define TAG             "{task_name.upper()}"
#define TASK_PERIOD_MS  {period_ms}
#define TASK_STACK      {stack_size}
#define TASK_PRIO       {priority}

static void {task_name}(void *pvParameters)
{{
    uint32_t iteration = 0;

    ESP_LOGI(TAG, "Task started");

    for (;;) {{
        ESP_LOGI(TAG, "Iteration %lu", (unsigned long)iteration++);
        vTaskDelay(pdMS_TO_TICKS(TASK_PERIOD_MS));
    }}
    vTaskDelete(NULL);
}}

void app_main(void)
{{
    xTaskCreate({task_name}, "{task_name}", TASK_STACK, NULL, TASK_PRIO, NULL);
}}
"""

    return code


# ---------------------------------------------------------------------------
# Coder Agent
# ---------------------------------------------------------------------------

class CoderAgent:
    """
    Generates production-quality C/C++ source code from a ``HardwareSpec``.

    Parameters
    ----------
    llm_backend:
        Callable with signature ``(system_prompt: str, user_message: str) -> str``
        that returns C/C++ source code as a plain string.
        Defaults to ``mock_doubao_call``.
    """

    SYSTEM_PROMPT = (
        "You are a senior Embedded Systems Software Engineer with deep expertise in "
        "ESP-IDF, STM32 HAL, and FreeRTOS.  "
        "You will receive a JSON hardware specification and MUST produce a complete, "
        "compilable C source file.  "
        "Requirements:\n"
        "  1. Include all necessary headers.\n"
        "  2. Use FreeRTOS primitives (xTaskCreate, vTaskDelay, semaphores, queues).\n"
        "  3. Guard every heap allocation (pvPortMalloc / malloc) with a NULL check.\n"
        "  4. Every FreeRTOS task function must call vTaskDelete(NULL) before returning.\n"
        "  5. Use mutex/semaphore to protect shared peripheral resources.\n"
        "  6. Follow MISRA-C naming conventions.\n"
        "  7. Do NOT include prose — return ONLY the C source code."
    )

    def __init__(self, llm_backend=None):
        self._llm = llm_backend or mock_doubao_call

    # ------------------------------------------------------------------
    def generate(self, spec: HardwareSpec, previous_feedback: Optional[str] = None) -> str:
        """
        Generate (or regenerate) C/C++ source code.

        Parameters
        ----------
        spec:
            Hardware specification from the Planner Agent.
        previous_feedback:
            Reviewer feedback from the previous iteration (if any).
            When provided, the LLM is instructed to fix the identified issues.

        Returns
        -------
        str
            Complete C/C++ source code as a plain string.
        """
        spec_json = json.dumps(spec, indent=2)

        if previous_feedback:
            user_message = (
                f"Hardware Specification:\n{spec_json}\n\n"
                f"IMPORTANT — The previous version of this code FAILED review with "
                f"the following feedback. You MUST address every point:\n\n"
                f"{previous_feedback}\n\n"
                f"Generate a corrected version of the complete C source file."
            )
        else:
            user_message = (
                f"Hardware Specification:\n{spec_json}\n\n"
                f"Generate the complete C source file."
            )

        return self._llm(self.SYSTEM_PROMPT, user_message)
